{
 "title": "Ceph - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_health_status)" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_monitor_quorum_count" }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_available_bytes)"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_capacity_bytes" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_cluster_used_bytes" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_available_bytes/ceph_cluster_capacity_bytes"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_osds_in" }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_osds - ceph_osds_in" }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_osd_up)" }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_osds_down" }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(ceph_osd_pgs)" }
   ]
  },
  {
   "title": "Agerage OSD Apply Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_perf_apply_latency_seconds)"
    }
   ]
  },
  {
   "title": "Agerage OSD Commit Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_perf_commit_latency_seconds)"
    }
   ]
  },
  {
   "title": "Average Monitor Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_monitor_latency_seconds)"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "ceph_cluster_available_bytes", "legendFormat": "Available" },
    { "expr": "ceph_cluster_used_bytes", "legendFormat": "Used" },
    { "expr": "ceph_cluster_capacity_bytes", "legendFormat": "Total Capacity" }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "ceph_client_io_write_ops", "legendFormat": "Write" },
    { "expr": "ceph_client_io_read_ops", "legendFormat": "Read" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "ceph_client_io_write_bytes", "legendFormat": "Write" },
    { "expr": "ceph_client_io_read_bytes", "legendFormat": "Read" }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_cluster_objects", "legendFormat": "Total" },
    { "expr": "ceph_degraded_objects", "legendFormat": "Degraded" },
    { "expr": "ceph_misplaced_objects", "legendFormat": "Misplaced" }
   ]
  },
  {
   "title": "Apply latency per OSD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_perf_apply_latency_seconds",
     "legendFormat": "{{instance}} {{osd}}"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_stuck_degraded_pgs", "legendFormat": "Degraded" },
    { "expr": "ceph_stuck_stale_pgs", "legendFormat": "Stale" },
    { "expr": "ceph_stuck_unclean_pgs", "legendFormat": "Unclean" },
    { "expr": "ceph_stuck_undersized_pgs", "legendFormat": "Undersized" }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ceph_osd_pgs)", "legendFormat": "Total" },
    { "expr": "ceph_degraded_pgs", "legendFormat": "Degraded" },
    { "expr": "ceph_stale_pgs", "legendFormat": "Stale" },
    { "expr": "ceph_unclean_pgs", "legendFormat": "Unclean" },
    { "expr": "ceph_undersized_pgs", "legendFormat": "Undersized" },
    {
     "expr": "ceph_stuck_degraded_pgs + ceph_stuck_stale_pgs + ceph_stuck_unclean_pgs + ceph_stuck_undersized_pgs",
     "legendFormat": "Stuck"
    }
   ]
  },
  { "title": "Recovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_recovery_io_bytes", "legendFormat": "Bytes" }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_recovery_io_keys", "legendFormat": "Keys" }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_recovery_io_objects", "legendFormat": "Objects" }
   ]
  }
 ]
}