{
 "title": "Nodes",
 "description": "Dashboard to for node information",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=~\"$server\"}[5m])))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$server\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "avg(node_load5{instance=~\"$server\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "avg(node_load15{instance=~\"$server\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemFree{instance=~\"$server\"} - node_memory_Buffers{instance=~\"$server\"} - node_memory_Cached{instance=~\"$server\"})",
     "legendFormat": "memory used"
    },
    {
     "expr": "avg(node_memory_Buffers{instance=~\"$server\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "avg(node_memory_Cached{instance=~\"$server\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "avg(node_memory_MemFree{instance=~\"$server\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "-/+ buffers/cache",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemFree{instance=~\"$server\"}  - node_memory_Buffers{instance=~\"$server\"} - node_memory_Cached{instance=~\"$server\"}) / node_memory_MemTotal{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read{instance=~\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written{instance=~\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_ms{instance=~\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\",instance=~\"$server\"}) - sum(node_filesystem_free{device!=\"rootfs\",instance=~\"$server\"})) / sum(node_filesystem_size{device!=\"rootfs\",instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(device) (rate(node_network_receive_bytes{instance=~\"$server\",device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(device) (rate(node_network_transmit_bytes{instance=~\"$server\",device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}